(
 (stanzas
 (
(CPP PROLOGUE
   "
#include <stdio.h>
#include <string>
#include <unistd.h>
#include <ostream>
#include <iostream>
#include <vector>

#include \"rocksdb/comparator.h\"
#include \"rocksdb/db.h\"
#include \"rocksdb/iterator.h\"
#include \"rocksdb/write_batch.h\"
#include \"ocaml_rocksdb.inc\"
#include \"somecode.h\"
#include \"cppffi.h\"
")
  (TYPEDEF
  ((mltype (EXP int))
   (cpptype (ID size_t))
   (name size_t)))



   (FOREIGN
    ((ID std::string))
    somecode_foo
    (((PRIM INT) n))
     "_res0 = somecode::foo(n); ")
   )
  )
 )
