(
 (stanzas
 (
(CPP PROLOGUE
   "
#include <stdio.h>
#include <string>
#include <unistd.h>
#include <ostream>
#include <iostream>
#include <vector>

#include \"somecode.h\"
#include \"cppffi.h\"
")
  (TYPEDEF
   ((mltype (CONCRETE INT64))
   (cpptype (ID size_t))
   (name size_t)))
 
   (FOREIGN
    ((ID std::string))
    somecode_foo
    (((PRIM INT) n))
     "_res0 = somecode::foo(n); ")

   (FOREIGN
    ((PRIM INT))
    somecode_int32_to_int
    (((PRIM INT32) n))
     "_res0 = somecode::int32_to_int(n); ")

    (FOREIGN
     ((TYCON std::optional ((PRIM INT))))
     somecode_int32_option_to_int_option
     (((TYCON std::optional ((PRIM INT32))) n))
     "_res0 = somecode::int32_option_to_int_option(n); ")

    (FOREIGN
     ((TYCON std::optional ((PRIM INT))))
     somecode_roundtrip_int_option
     (((TYCON std::optional ((PRIM INT))) n))
     "_res0 = somecode::roundtrip_int_option(n); ")

   (FOREIGN
    ((PRIM INT32))
    somecode_int_to_int32
    (((PRIM INT) n))
     "_res0 = somecode::int_to_int32(n); ")

   (FOREIGN
    ((TYCON "std::tuple" ((ID std::string) (PRIM INT))))
    somecode_bar
    (((ID std::string) s) ((PRIM INT) n))
    "_res0 = somecode::bar(s, n); ")
 
   (FOREIGN
    ((ID std::string))
    somecode_size_t_to_string
    (((ID size_t) n))
     "_res0 = somecode::size_t_to_string(n); ")


  (TYPEDEF
   ((mltype (CONCRETE CHAR)) (cpptype (ID somecode::WALRecoveryMode)) (name wal_recovery_mode_t)))

 (CPP2ML (ID wal_recovery_mode_t) "sentinel_INT s0;
   _mlvalue = c2ml(s0,static_cast<int>(_cvalue));")
  (ML2CPP (ID wal_recovery_mode_t) "{ sentinel_INT _s0;
   char xx ; ml2c(_s0, _mlvalue, &xx); *_cvaluep = static_cast<somecode::WALRecoveryMode>(xx) ; }")

   (FOREIGN
    ((ID wal_recovery_mode_t))
    somecode_wal_recovery_mode_from_int
    (((PRIM INT) n))
     "_res0 = somecode::wal_recovery_mode_from_int(n); ")

   )
  )
 )
