(
 (stanzas
 (
(CPP PROLOGUE
   "
#include <stdio.h>
#include <string>
#include <unistd.h>
#include <ostream>
#include <iostream>
#include <vector>

#include \"somecode.h\"
#include \"cppffi.h\"
")

  (TYPEDEF
   ((mltype (CONCRETE INT64))
   (cpptype (ID size_t))
   (name size_t)))

   (FOREIGN
    ((ID std::string))
    somecode_foo
    (((PRIM INT) n))
     "_res0 = somecode::foo(n); ")

   (FOREIGN
    ((PRIM INT))
    somecode_int32_to_int
    (((PRIM INT32) n))
     "_res0 = somecode::int32_to_int(n); ")

    (FOREIGN
     ((TYCON std::optional ((PRIM INT))))
     somecode_int32_option_to_int_option
     (((TYCON std::optional ((PRIM INT32))) n))
     "_res0 = somecode::int32_option_to_int_option(n); ")

    (FOREIGN
     ((TYCON std::optional ((PRIM INT))))
     somecode_roundtrip_int_option
     (((TYCON std::optional ((PRIM INT))) n))
     "_res0 = somecode::roundtrip_int_option(n); ")

    (FOREIGN
     ((TYCON std::optional ((ID std::string))))
     somecode_roundtrip_string_option
     (((TYCON std::optional ((ID std::string))) n))
     "_res0 = somecode::roundtrip_string_option(n); ")

   (FOREIGN
    ((PRIM INT32))
    somecode_int_to_int32
    (((PRIM INT) n))
     "_res0 = somecode::int_to_int32(n); ")

   (FOREIGN
    ((TYCON "std::tuple" ((ID std::string) (PRIM INT))))
    somecode_bar
    (((ID std::string) s) ((PRIM INT) n))
    "_res0 = somecode::bar(s, n); ")
 
   (FOREIGN
    ((ID std::string))
    somecode_size_t_to_string
    (((ID size_t) n))
     "_res0 = somecode::size_t_to_string(n); ")


  (TYPEDEF
   ((mltype (CONCRETE CHAR)) (cpptype (ID somecode::WALRecoveryMode)) (name wal_recovery_mode_t)))

 (CPP2ML (ID wal_recovery_mode_t)
  "_mlvalue = c2ml(sentinel_INT(),static_cast<int>(_cvalue));")
 (ML2CPP (ID wal_recovery_mode_t)
  "{ char xx ; ml2c(sentinel_INT(), _mlvalue, &xx); *_cvaluep = static_cast<somecode::WALRecoveryMode>(xx) ; }")

   (FOREIGN
    ((ID wal_recovery_mode_t))
    somecode_wal_recovery_mode_from_int
    (((PRIM INT) n))
     "_res0 = somecode::wal_recovery_mode_from_int(n); ")

    (STRUCT
     ((modname ST0)
      (name t)
      (members
       (
	((PRIM BOOL) b)
	((PRIM UCHAR) uc)
	))))

    (FOREIGN ((ID ST0_t))
     somecode_roundtrip_ST0_t
     (((ID ST0_t) st))
     " _res0 = st ;"
     )


    (STRUCT
     ((modname ST)
      (name t)
      (members
       (
	((PRIM BOOL) b)
	((PRIM UCHAR) uc)
	((PRIM INT) n)
	((PRIM UINT64) nL)
	((ID std::string) s)
	((ID size_t) sz)
	))))

    (FOREIGN ((ID ST_t))
     somecode_roundtrip_ST_t
     (((ID ST_t) st))
     " _res0 = st ;"
     )

  (TYPEDEF
   ((mltype (CONCRETE INT64))
   (cpptype (ID short))
   (name short_t)))

 (CPP2ML (ID short_t)
  "_mlvalue = c2ml(sentinel_INT64(),static_cast<int64_t>(_cvalue));")
 (ML2CPP (ID short_t)
  "{ int64_t xx ; ml2c(sentinel_INT64(), _mlvalue, &xx); *_cvaluep = static_cast<short>(xx) ; }")

    (FOREIGN
     ((ID short_t))
     somecode_roundtrip_short_t
     (((ID short_t) n))
     "_res0 = n; ")

   (TYPEDEF
    ((mltype (ABSTRACT stt_id))
     (cpptype (PTR (ID ST_t))) 
     (name stt_id)))
   (ML2CPP (ID stt_id) "ml2c_owned_pointer(_mlvalue, _cvaluep);")

   (TYPEDEF
    ((mltype (CONCRETE (OPTION (OTHER stt_id))))
     (cpptype (TYCON std::optional ((ID stt_id))))
     (name stt_id_opt)))

    (FOREIGN
     ((TYCON std::optional ((ID stt_id))))
     somecode_stt_make
     ()
     "_res0 = std::optional(new ST_t()); ")

    (FOREIGN
     ((ID stt_id_opt))
     somecode_stt_make_2
     ()
     "_res0 = std::optional(new ST_t()); ")

   (ATTRIBUTE
    ((target stt_id) (aname nL) (fprefix somecode_) (cpptype (PRIM UINT64))))
   (ATTRIBUTE
    ((target stt_id) (aname b) (fprefix somecode_) (cpptype (PRIM BOOL))))

   (TYPEDEF
    ((mltype (CONCRETE (TUPLE (INT STRING))))
     (cpptype (ID somecode::something))
     (name something)))

  (CPP2ML (ID something)
     "int n = _cvalue.n;
      std::string s = _cvalue.s ;
   _mlvalue = c2ml(sentinel_INT(), sentinel_GENERIC(), n, s) ;")

   (FOREIGN
    ((ID something))
     somecode_via_something
    (((PRIM INT) n) ((ID std::string) s))
     "somecode::something st(n, s);
      _res0 = st;
")
   )
  )
 )
